Remove deprecated compiler check
As of brew 2.0.0, this compiler check is deprecated. See:
https://github.com/Homebrew/homebrew-core/pull/36362

When trying to `bin/install` in e.g. _web_, one sees messages like:
```
Error: Invalid formula: .../Formula/vowpal-wabbit-7.10.rb
Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the opendoor-labs/tap tap:
  .../opendoor-labs/homebrew-tap/Formula/vowpal-wabbit-7.10.rb:19
```